version: '3'
services:
  customer:
    image: registry.springhome.com.br/customer:0.0.1-SNAPSHOT
    container_name: customer-api
    restart: always
    ports:
      - 8080:8080
      - 80:8080
    #environment:
      #- DISCOVERY_URL=http://homolog.springhome.com.br:8761/eureka/
      #- MONGO_DEFAULT_URI=mongodb://user_crud:product@ds241039.mlab.com:41039/customer
      #- NON_SECURE_PORT=88080
      #- DOMAIN_NAME=51.15.205.247
    networks:
      - aws_customer
  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    #volumes:
    #    - /var/redis:/redis
    networks:
      - aws_customer

networks:
  aws_customer:
    driver: bridge